# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170428_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, help_text='Opción mostrada solo en la administración', verbose_name='Es estudiante'),
        ),
    ]
