# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestionanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='testquestionanswer',
            name='question',
        ),
        migrations.RenameField(
            model_name='testoption',
            old_name='question',
            new_name='test',
        ),
        migrations.AddField(
            model_name='story',
            name='per_game_questions_number',
            field=models.IntegerField(default=5, verbose_name='Número de preguntas por partida'),
        ),
        migrations.AddField(
            model_name='testoption',
            name='is_answer',
            field=models.BooleanField(default=False, verbose_name='Solución a la pregunta tipo test (puede haber varias)'),
        ),
        migrations.DeleteModel(
            name='TestQuestionAnswer',
        ),
    ]
