# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20170428_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(default=1, upload_to='', verbose_name='Imagen de portada de la historia (500 x 500)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='end_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Imagen final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='end_text',
            field=models.TextField(default=1, help_text='Ejemplo: ¡Gracias a ti Torcuato lo ha logrado!', verbose_name='Texto que da fin a la historia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='introduction_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Imagen que se muestra al inicio de la partida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='introduction_text',
            field=models.TextField(default=1, help_text='Es el texto que se muestra al iniciar el juego', verbose_name='Texto de introducción a la historia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='context',
            field=models.TextField(help_text='Ejemplo: Florinda y Torcuato están preparándose para una aventura, ¿te animas a ayudarlos?', verbose_name='Contexto en el que se desarrolla el juego'),
        ),
    ]
