# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20170428_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheat',
            name='cheat_text',
            field=models.TextField(default=1, verbose_name='Texto de la pista'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='story',
            field=models.ForeignKey(help_text='Historia a la que pertenece la pregunta', on_delete=django.db.models.deletion.CASCADE, to='question.Story'),
        ),
    ]
