# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20170428_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testoption',
            name='test',
        ),
        migrations.AddField(
            model_name='testoption',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(0, 'Texto'), (1, 'Cuestionario')], default=0, help_text='Texto, cuestionario, etc', max_length=128, verbose_name='Tipo de pregunta'),
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
