# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20170428_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('CUESTIONARIO', 'Cuestionario')], default='TEXTO', help_text='Texto, cuestionario, etc', max_length=128, verbose_name='Tipo de pregunta'),
        ),
    ]
