# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20170504_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagen de portada de la historia (500 x 500)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='end_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagen final'),
        ),
        migrations.AlterField(
            model_name='story',
            name='introduction_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagen que se muestra al inicio de la partida'),
        ),
    ]
