# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20170504_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='end_image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='end_text',
        ),
        migrations.RemoveField(
            model_name='story',
            name='introduction_image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='introduction_text',
        ),
        migrations.RemoveField(
            model_name='story',
            name='per_game_questions_number',
        ),
        migrations.AddField(
            model_name='story',
            name='questions_number',
            field=models.IntegerField(default=1, editable=False, help_text='Número autogenerado de preguntas de una historia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen que se mostrará en la cabecera de la pregunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('CUESTIONARIO', 'Cuestionario'), ('VINETA', 'Viñeta')], default='TEXTO', help_text='Texto, cuestionario, etc', max_length=128, verbose_name='Tipo de pregunta'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers', verbose_name='Imagen de portada de la historia (500 x 500)'),
        ),
    ]
