# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170506_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testoption',
            name='is_answer',
            field=models.BooleanField(default=False, verbose_name='Solo puede haber una solución'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterUniqueTogether(
            name='testoption',
            unique_together=set([('question', 'is_active')]),
        ),
    ]
