# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170506_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testoption',
            name='is_answer',
            field=models.BooleanField(default=False, verbose_name='¿Es esta la solución? (debe ser única)'),
        ),
        migrations.AlterUniqueTogether(
            name='testoption',
            unique_together=set([('question', 'is_answer')]),
        ),
    ]
