# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170506_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
