# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
