# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 18:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170516_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attemps',
            field=models.IntegerField(default=3, help_text='El usuario podrá fallar tantas veces como este valor indique', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de intentos permitidos en la pregunta'),
        ),
    ]
