# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170516_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='attemps',
            new_name='attempts',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='attempts_made',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
