# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 23:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20170516_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestionanswer',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
