# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 10:26
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_question_external_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='external_image',
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
