# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('order', models.IntegerField(default=0, verbose_name='Órden de las pistas, del 0 a n')),
                ('cheat_text', models.TextField(verbose_name='Texto de la pista')),
            ],
            options={
                'verbose_name_plural': 'Pistas',
                'verbose_name': 'Pista',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_finished', models.BooleanField(default=False, verbose_name='¿Ha terminado el juego?')),
                ('actual_question', models.IntegerField(default=0, editable=False, verbose_name='Pregunta actual, desde 1 hasta num pregs')),
            ],
            options={
                'verbose_name_plural': 'Partidas',
                'verbose_name': 'Partida',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden de la pregunta en el juego')),
                ('question_type', models.CharField(choices=[('TEXTO', 'Texto'), ('CUESTIONARIO', 'Cuestionario'), ('VINETA', 'Viñeta')], default='TEXTO', help_text='Texto, cuestionario, etc', max_length=128, verbose_name='Tipo de pregunta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen que se mostrará en la cabecera de la pregunta')),
                ('question_text', models.TextField(verbose_name='Enunciado de la pregunta.')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'verbose_name': 'Pregunta',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre de la historia')),
                ('context', models.TextField(help_text='Ejemplo: Florinda y Torcuato están preparándose para una aventura, ¿te animas a ayudarlos?', verbose_name='Contexto en el que se desarrolla el juego')),
                ('min_age', models.IntegerField(default=10, verbose_name='Edad mínima recomendada')),
                ('max_age', models.IntegerField(default=13, verbose_name='Edad máxima recomendada')),
                ('questions_number', models.IntegerField(editable=False, help_text='Número autogenerado de preguntas de una historia')),
                ('cover', models.ImageField(blank=True, upload_to='covers', verbose_name='Imagen de portada de la historia (500 x 500)')),
            ],
            options={
                'verbose_name_plural': 'Historias',
                'verbose_name': 'Historia',
            },
        ),
        migrations.CreateModel(
            name='TestOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Quiere que esta opción sea visible?')),
                ('is_answer', models.BooleanField(default=False, verbose_name='Solución a la pregunta tipo test (puede haber varias)')),
                ('text', models.CharField(max_length=512, verbose_name='Opción de pregunta tipo test')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Question')),
            ],
            options={
                'verbose_name_plural': 'Opciones a responder en pregunta de tipo test',
                'verbose_name': 'Opción a responder en pregunta de tipo test',
            },
        ),
        migrations.CreateModel(
            name='TextQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('answer', models.TextField(verbose_name='Respuesta a la pregunta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Question')),
            ],
            options={
                'verbose_name_plural': 'Preguntas de tipo texto',
                'verbose_name': 'Pregunta de tipo texto',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='story',
            field=models.ForeignKey(help_text='Historia a la que pertenece la pregunta', on_delete=django.db.models.deletion.CASCADE, to='game.Story'),
        ),
        migrations.AddField(
            model_name='game',
            name='story',
            field=models.ForeignKey(help_text='Historia seleccionada por el jugador', on_delete=django.db.models.deletion.CASCADE, to='game.Story'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(help_text='Usuario que juega la partida', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheat',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('story', 'order')]),
        ),
    ]
