# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20170428_1100'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Preguntas de la partida',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AddField(
            model_name='game',
            name='story',
            field=models.ForeignKey(default=1, help_text='Historia seleccionada por el jugador', on_delete=django.db.models.deletion.CASCADE, to='question.Story'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(help_text='Usuario que juega la partida', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamequestions',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='gamequestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
