# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170428_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamequestions',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamequestions',
            name='question',
        ),
        migrations.AddField(
            model_name='game',
            name='actual_question',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='GameQuestions',
        ),
    ]
