# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170504_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_started',
        ),
        migrations.AlterField(
            model_name='game',
            name='actual_question',
            field=models.IntegerField(default=0, editable=False, verbose_name='Pregunta actual, desde 1 hasta num pregs'),
        ),
    ]
