# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170505_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textquestionanswer',
            options={'verbose_name': 'Respuesta a pregunta de tipo texto', 'verbose_name_plural': 'Respuestas a preguntas de tipo texto'},
        ),
        migrations.AlterField(
            model_name='cheat',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Órden de las pistas, del 1 a n'),
        ),
        migrations.AlterUniqueTogether(
            name='cheat',
            unique_together=set([('question', 'order')]),
        ),
    ]
