# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170505_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='cheat',
            name='order',
            field=models.IntegerField(default=1, help_text='No repitas el orden de las pistas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Órden de las pistas, del 1 a n'),
        ),
    ]
