# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170506_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheat',
            old_name='cheat_text',
            new_name='text',
        ),
    ]
